// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Akka.Persistence.Devart.Oracle")]
[assembly: AssemblyProductAttribute("Akka.Persistence.Devart.Oracle")]
[assembly: AssemblyDescriptionAttribute("An Oracle Akka.NET Persistence plugin using the Oracle.ManagedDataAccess libraries.")]
[assembly: AssemblyVersionAttribute("0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0")]
[assembly: AssemblyInformationalVersionAttribute("0.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.0";
    }
}
